name: guidance
description: Application of children career guidance base on programming

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.2.6
  provider: ^6.0.5
  path_provider: ^2.0.14
  flutter_svg: ^2.0.4
  shimmer: ^2.0.0
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  path: ^1.8.2
  shared_preferences: ^2.1.0
  flutter_local_notifications: ^13.0.0
  cupertino_icons: ^1.0.5
  ionicons: ^0.2.2
  google_fonts: ^4.0.3
  carousel_slider: ^4.2.1
  percent_indicator: ^4.2.3
  connectivity_plus: ^3.0.3
  video_player: ^2.6.1
  chewie: ^1.4.0
  http: ^0.13.5
  fluttertoast: ^8.2.1
  lottie: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logod.png"
  adaptive_icon_background: "assets/logo/logod_background.png"
  adaptive_icon_foreground: "assets/logo/logod_foreground.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/profile.png
    - assets/svg/books-svgrepo-com.svg
    - assets/svg/blob-haikei.svg
    - assets/svg/books-book-svgrepo-com.svg
    - assets/svg/achievement-challenge-medal-svgrepo-com.svg
    - assets/svg/challenge-environment-flag-forest-hill-mountain-svgrepo-com.svg
    - assets/json/1818-success-animation.json
    - assets/json/11272-party-popper.json
    - assets/json/55867-congratulation.json
    - assets/json/59344-congratulation-badge-animation.json

